### ISSUE TITLE
HTML fields not well translated

### ISSUE THREAD

**Issue by qtheuret** [OCA/connector-prestashop#120]
The HTML fields (like `description_html` or `description_short_html`) on the `prestashop.product.template` model are not well translated when imported.

To reproduce this issue : 

1. Create a Prestashop instance with two langs for the same shop (i.e. English / French).
2. Create a product and set a description and/or a short description
3. Sync. this product to Odoo
4. In the `prestashop.product.template` record, the value of the description / short description is in French and if you check the translations values, all have the same source terms and translation value.

Have you faced the same issue ?

**Comment by pedrobaeza** [comment]
AFAIK, that fields use `html_translate=True`, which means the translation is split into pieces. That can be one reason.

**Comment by Jerther** [comment]
Hi @qtheuret I'm facing a similar issue in Odoo 15.0 with `mail.activity`:

`note = fields.Html('Note', sanitize_style=True)`

@pedrobaeza This field does not use `translate=html_translate` so that's not the problem.

The suggested fix seems to work:

`note = fields.Text('Note', translate=True)`

But I find it's an ugly monkey patch... Have you found a better way of fixing the problem since 2019?

**Comment by pedrobaeza** [comment]
AFAIK, `field.Html` are translate=html_translate by default.

**Comment by omalbastin** [comment]
im also facing same issue in odoo 14 for a prestashop instance with 4 lang(FR, CH, EN and IT). description_html and short_description_html fields are both Html fields. It didnt had html_translate. I have added that. but still it is not geting translated
